### ISSUE TITLE
Schedule for the week!

### ISSUE THREAD

**Issue by Jen-Harris** [InFact-coop/DAAT#1]
__Monday:__ Workshop and PO training
__Tuesday:__ Design and align
__Wednesday & Thursday:__ Prototype!
__Friday:__ Present, review, amend & test - @cjonesdaat when would work for you?

**Comment by Jen-Harris** [comment]
Hey @cjonesdaat, 
When would you like us to present the product to you on Friday? 
Do you have users coming in the afternoon? If so it would probably be best to do it earlier in the day. 
Let us know!

**Comment by cjonesdaat** [comment]
Hi Jen, we have users available first thing Friday morning 9 - 10 am would that be any good? or it would have to be late afternoon 3:30 - 4:30ish.

Most of the fundraising team in the office know how to complete the Volunteer form and we have Pete Mason our volunteer at home on standby to assist during though times also.

Please confirm which time slot would be best.

Regards

Cara

**Comment by Jen-Harris** [comment]
Hey @cjonesdaat, 
This is awesome news! 
I think that the afternoon slot would be best so we can have time to review the prototype and go through user testing with you in the morning? 

for user testing you will only be talking to 1 person at a time and each session takes 20-30 minutes. How many users were you planning on testing with tomorrow? We typically recommend 4-5 users to get the most thorough feedback. 

Would you like to go through how to do user testing this afternoon or tomorrow? And likewise with the prototype, would you like us to demo that tomorrow morning (we could do both together tomorrow morning)? We need the rest of today to complete the prototype. 

Jen

**Comment by cjonesdaat** [comment]
Hi Jen i'm in the office today so if you could give me a ring this afternoon and explain, I will then have to sort times out with the users for tomorrow afternoon.

**Comment by Jen-Harris** [comment]
Let's demo at 9:30 tomorrow if that's OK with you?  

Will follow up with user testing info on a new issue 👍

**Comment by cjonesdaat** [comment]
That time is fine Jen, thanks

**Comment by cjonesdaat** [comment]
Hi Jen, I'm trying to access the demo again and cant, its just taking me to blank hangout page... can you re-send me the links.

**Comment by cjonesdaat** [comment]
was it something like http://www.shurg.sh

**Comment by Jen-Harris** [comment]
Hi, Sorry for not being clear. the link is : https://DAAT.surge.sh

**Comment by Jen-Harris** [comment]
You can find the link at the top of the repository home page

**Comment by cjonesdaat** [comment]
All received thank you ; )

**Comment by cjonesdaat** [comment]
Hi Jen and Max, I just wanted to say a huge thank you for all the hard work you have put into the prototype.  We have all taken a look and added our comments. I have spoken to the CEO Helena regarding any next steps and senior management will be in contact in due course once all the options have been considered. I hope you have a lovely weekend, 
[CAST - APP - Volunteer Feedback.xlsx](https://github.com/InFact-coop/DAAT/files/1626874/CAST.-.APP.-.Volunteer.Feedback.xlsx)
![app incorrectly adding up with wrong decimal input](https://user-images.githubusercontent.com/35232062/34886967-c7a9049c-f7bc-11e7-9a96-dd47f4d1ad01.png)

**Comment by maxgerber** [comment]
@cjonesdaat this is fantastic and really thorough. We've both really enjoyed working on this project and look forward to chatting with you guys. Have a good weekend!
