### ISSUE TITLE
Initial Designs!

### ISSUE THREAD

**Issue by Jen-Harris** [InFact-coop/DAAT#3]
Hey @cjonesdaat!
We've been working on the designs today and are excited to share them with you. 
Throughout the designs we have taken into consideration the typical user and tried to accommodate their needs. For example:
* We have kept the minimum font size as 20px (normal websites are 16px)
* We have centred the information to keep attention focused
* We have kept buttons very large so they are obvious and easily clickable 
* We have tried to use simple language and kept minimal information on each page

The designs we've created are quite detailed and therefore not suitable to go through on github. Would we be able to have a call to run you through them? 

We've been creating the designs in 'Figma' which is a free design collaboration tool. So you can have a look at the designs there as well!: https://www.figma.com/file/fwT2i0RdpzhAEqLLm0qDjdU4/Devon-Air-Ambulance?node-id=0%3A1

**Comment by Jen-Harris** [comment]
Alongside this we have a few questions, which can be discussed here:

1. At the moment we are imagining that people cannot submit their forms if the numbers don't match. Is this what you had in mind, or should they still be able to submit? 
2. We've included and 'FAQ' page. If this is something you would like please let us know the copy for questions and answers. 
3. Are we going with the idea that volunteers can submit the forms multiple times a month? 

Thanks @cjonesdaat!

**Comment by cjonesdaat** [comment]
Hi Jen 

it would be best to call me as I have only 15 minutes before I leave the office.. 01392 466666 ext 122

**Comment by Jen-Harris** [comment]
Hey @cjonesdaat, I went through to your voicemail. 
If it's a bit rushed we can speak tomorrow morning? 
My number is 07766023236

**Comment by cjonesdaat** [comment]
Sorry Jen I was on the phone with one of our shop managers. I've just tried your number and its saying not recognised. If you wouldn't mind confirming ti will try again

**Comment by cjonesdaat** [comment]
[Box Collectors.docx](https://github.com/InFact-coop/DAAT/files/1615939/Box.Collectors.docx)
+

**Comment by cjonesdaat** [comment]
![logo march 2015 large](https://user-images.githubusercontent.com/35232062/34733031-e9426194-f55e-11e7-9bf7-1448ff191c2e.jpg)

**Comment by cjonesdaat** [comment]
![daa_strip_blue_072](https://user-images.githubusercontent.com/35232062/34733066-fe0983d2-f55e-11e7-8759-ebebcec583bb.jpg)
![daa_strip_red_032 a4](https://user-images.githubusercontent.com/35232062/34733073-031c11e6-f55f-11e7-8999-eeb0c363f81c.jpg)
![daa_strip_red_032 a5](https://user-images.githubusercontent.com/35232062/34733075-069e5478-f55f-11e7-896f-3cc5a75d23ce.jpg)
![daa_strip_taupe_7504](https://user-images.githubusercontent.com/35232062/34733081-08dac80c-f55f-11e7-9828-029ec4249669.jpg)

**Comment by cjonesdaat** [comment]
Hi Jen a couple of things @Jen-Harris 

Page 1 - 

Instead of ‘Record New Box’  to Record Box Collection

Instead of the automated date filled please call it Date of Collection and allow the volunteer    in input the date (is there a pop up calendar available?)

There also needs to be a link on this page for donations so perhaps a button ‘Add a Donation’
The add donation then need to take us to another page which we can fill in the Donation Form, I did printout a copy for you on Monday. The form needs to be pretty much the same.

Can we also add a small section for Merchandise, it might its better to do another button to another page ‘Merchandise (all which is needed in on the original VMR form)

Instead of Save can you do Save and Exit and another button saying Save and add another box

Page 3 – 

Donations and Merchandise will then need to be added to the summary page.

Hope this is ok.. I’m out of the office now for a couple of hours but will be back this afternoon. Thanks

**Comment by Jen-Harris** [comment]
Hey @cjonesdaat, 

Thanks for the extra input. We can certainly do:
* "Record box collection"
* Date changes
* Save buttons

@maxgerber and I have had a chat about the additional pages and unfortunately it won't be possible to include them given the time constraints. We want to be able to give you a working prototype with a clear feature that you can test with users on Friday. I hope this is OK? One alternative is that we could mock these pages up in Figma for you if we have time, but it won't be part of the working prototype. 

It would certainly be feasible to add this in the future though if you were interested in progressing to a 2 week build sprint. Is this something you would be interested in?

**Comment by cjonesdaat** [comment]
Hi Jen could you call me on 07944 392 667?

Sent from my iPhone

On 10 Jan 2018, at 10:40, Jen Harris <notifications@github.com<mailto:notifications@github.com>> wrote:


Hey @cjonesdaat<https://github.com/cjonesdaat>,

Thanks for the extra input. We can certainly do:

  *   "Record box collection"
  *   Date changes
  *   Save buttons

@maxgerber<https://github.com/maxgerber> and I have had a chat about the additional pages and unfortunately it won't be possible to include them given the time constraints. We want to be able to give you a working prototype with a clear feature that you can test with users on Friday. I hope this is OK? One alternative is that we could mock these pages up in Figma for you if we have time, but it won't be part of the working prototype.

It would certainly be feasible to add this in the future though if you were interested in progressing to a 2 week build sprint. Is this something you would be interested in?
